### ISSUE TITLE
Баг с метрикой на новых версиях

### ISSUE THREAD

**Issue by InterVi** [fromgate/CPFix-0.3.2#2]
Зависимости не приложены, даже самому не переделать. А плагин очень нужный.

`[03:35:26] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5" 
[03:35:26] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin CPFix v0.4.0 generated an exception while executing task 28
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at fromgate.cpfix.MetricsLite.postPlugin(MetricsLite.java:285)
    at fromgate.cpfix.MetricsLite.access$3(MetricsLite.java:278)
    at fromgate.cpfix.MetricsLite$1.run(MetricsLite.java:173)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more`

**Comment by fromgate** [comment]
Я в шоке. :) 
А зачем он на 1.10????

**Comment by fromgate** [comment]
@InterVi 
Короче, вот плагин с обновленным MetricsLite:
https://dev.bukkit.org/bukkit-plugins/cpfix/files/11-cpfix-v0-4-1/
Вот новые исходники (эти удалю потом):
https://github.com/fromgate/CPFix

Ну и всё-таки, зачем этот плагин на 1.10? 
Может какие-то функции выпилить и оставить только то, что нужно?

**Comment by InterVi** [comment]
А разве проблемы кодировки пофикшены в самом ядре? Я просто не в курсе, по привычке ставлю его.

**Comment by fromgate** [comment]
Ну главная проблема был с LWJGL - она была решена, кажется, ещё во времена 1.6. 
Т.е. теоретически сейчас CPFix актуален в том случае, если на сервере стоит старая карта, которая создана во времена 1.5 (или раньше) и там на табличках/книгах остались кривые кодировки.

Ну и в теории (я, признаю честно не пробовал в последних версиях спигота) CPFix может корректировать кодировку в консоли/логе  - если к примеру нужно чтобы в лог писалось в 1251-й кодировке и при этом в 866-й в консоль.
